export const runtime = "edge";
import type { Metadata } from "next";
import "./globals.css";
import { vazir } from "./fonts";
import Providers from "./Providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body className={vazir.className}>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
