export const runtime = "edge";
import type { Metadata } from "next";
import "./globals.css";
import { vazirmatn } from "./fonts";
import Providers from "./Providers";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
  title: "استاندار",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <meta
        name="viewport"
        content="width=device-width, initial-scale=1, maximum-scale=1"
      ></meta>
      <body className={`${vazirmatn.className} ${vazirmatn.variable}`}>
        <Providers>{children}</Providers>
        <Toaster richColors className="font-vazir" theme="light" />
      </body>
    </html>
  );
}
